### ISSUE TITLE
ClientDetector Bug

### ISSUE THREAD

**Issue by NormanLord** [CraptiCraft-Development/PosCommands#1]
First of all, I create issues here because there is no issues can be created in that project.
Next I want to report the bug of ClientDetector. I run it on purpur which is a fork of paper in 1.20.1.  The server would break after someone who have certain perms quited the game. The controller says the connection has been retired after I(OP) quited game.

**Comment by Loving11ish** [comment]
Ok, Please can you provide a full error report please along with Server version (using /version), Java runtime version please and ClientDetector version please.

**Comment by NormanLord** [comment]
Here's the console output.It happended after I quit the game. Sometimes that bug doesn't happen so I find the earlier report of my server.After this exception ,server would shot down.
[09:08:20] [Server thread/INFO]: NormanChris lost connection: Disconnected
[09:08:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Already retired
	at io.papermc.paper.threadedregions.EntityScheduler.retire(EntityScheduler.java:66) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.world.entity.Entity.retireScheduler(Entity.java:4867) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4852) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.server.players.PlayerList.lambda$remove$2(PlayerList.java:641) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:632) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:585) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2216) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2195) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:827) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1614) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2001]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by NormanLord** [comment]
Server: purpur 1.20.1 -2000 
Java: java 17
CilentDetector:published in 6/25

**Comment by NormanLord** [comment]
I used the latest version of CilentDetector, everything looks fine now.
